version: 0.1

environment_variables:
  plaintext:
    AWS_DEFAULT_REGION: "us-east-1"
    SNS_TOPIC_ARN: "arn:aws:sns:us-east-1:649407818518:code-build-message"
    
phases:
  build:
    commands:
      - echo Start build and push of DockerImage
      - echo Code build-id $CODEBUILD_BUILD_ID
      - i=$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}');docker build -t abirdatta/poc:$i .
      - docker login --username=abirdatta --email="abirdatta.in@gmail.com" --password="dockerhub123"
      - i=$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}');docker push abirdatta/poc:$i
      - echo Docker build and push done
      - i=$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}');./update-ecs-cloudformation-stack.sh MyStack 'https://s3.amazonaws.com/ecs-cloudformation-templates/ecs-stack-template.json' $i
  post_build:
    commands:
      - echo Nothing to do in post build
