version: 0.1

environment_variables:
  plaintext:
    AWS_DEFAULT_REGION: "us-east-1"
    SNS_TOPIC_ARN: "arn:aws:sns:us-east-1:649407818518:code-build-message"
    
phases:
  build:
    commands:
      - echo Start build and push of DockerImage
      - echo Code build-id $CODEBUILD_BUILD_ID
      - i=$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}');docker build -t abirdatta/poc:v$i .
      - docker login --username=abirdatta --email="abirdatta.in@gmail.com" --password="dockerhub123"
      - docker push abirdatta/poc
      - echo Docker build and push done
      - d=$CODEBUILD_BUILD_ID; echo Variable d id $d
      - echo Variable I is $i
      - sed -e "s/\${BUILD_NUMBER}/$i/g" create-payload.json > payload.json
  post_build:
    commands:
      - echo Nothing to do in post build
artifacts:
  files:
    - payload.json
