version: 0.1

environment_variables:
  plaintext:
    AWS_DEFAULT_REGION: "us-east-1"
    SNS_TOPIC_ARN: "arn:aws:sns:us-east-1:649407818518:code-build-message"
    
phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
  post_build:
    commands:
      - echo Build completed on `date` , Start build and push of DockerImage 
      - docker build -t abirdatta/poc:v$CODEBUILD_BUILD_ID .
      - docker login --username=abirdatta --email="abirdatta.in@gmail.com" --password="dockerhub123"
      - docker push abirdatta/poc
      - echo Docker build and push done
      - sed -e "s/\${BUILD_NUMBER}/$CODEBUILD_BUILD_ID/g" create-payload.json > payload.json
      - messageText="$(cat payload.json)";aws sns publish --topic-arn $SNS_TOPIC_ARN --subject 'AWS CodeBuild - Build Completed' --message "${messageText}"
artifacts:
  files:
    - payload.json 